- hosts: webservers

  tasks:
    - name: load envs
      ansible.builtin.template:
        src: ./template/.env.j2
        dest: .env

    - name: deploy redmine
      community.docker.docker_container:
        name: redmine
        image: "redmine:latest"
        restart_policy: always
        state: started
        recreate: true
        env_file: .env
        ports:
          - "{{ redmine_port }}:3000"
      become: true