- hosts: all

  roles:
    - role: geerlingguy.pip
      vars:
        pip_install_packages:
          - name: docker

  tasks:
    - name: install pip docker
      ansible.builtin.pip:
        name: docker
