- hosts: webservers
  gather_facts: no
  become: yes

  tasks:
    - name: add user
      ansible.builtin.user:
        name: "{{ username }}"
        state: present
        groups: root
    - name: add public ssh key
      ansible.posix.authorized_key:
        user: "{{ username }}"
        state: present
        key: "{{ lookup('file', '/home/{{ username }}/.ssh/id_rsa.pub') }}"