DB_POSTGRES: "{{ VAULT_DB_POSTGRES }}"
DB_DATABASE: "{{ VAULT_DB_DATABASE }}"
DB_USERNAME: "{{ VAULT_DB_USERNAME }}"
DB_PASSWORD: "{{ VAULT_DB_PASSWORD }}"
DB_PORT: "{{ VAULT_DB_PORT }}"
redmine_port: 3000