name: deploy application

on:
  push:
    branches:
      - 'master'
    paths:
      - 'group_vars/**'
    tags:
      - '**'

jobs:
  push-app:
    runs-on: ubuntu-latest

    steps:
      - name: copy git directory
        uses: actions/checkout@v3

      - name: Install SSH client
        run: sudo apt-get update && sudo apt-get install -y openssh-client

      - name: install roles
        run: make install-role

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: prepare servers
        env:
          VAULT_PASSWORD: ${{ secrets.VAULT_SECRET }}
        run: make prepare-servers PASSWORD_FILE=<(echo "$VAULT_PASSWORD")

      - name: Clean up SSH
        run: |
          rm -f ~/.ssh/id_rsa